<a href="https://colab.research.google.com/github/Shaikh-Uzair-Ahmed/1BM23CS307/blob/ML/1BM23CS307_LAB2-Linear-multiple-Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df = pd.read_csv('/content/canada_per_capita_income.csv')
df.head()

   year  per capita income (US$)
0  1970              3399.299037
1  1971              3768.297935
2  1972              4251.175484
3  1973              4804.463248
4  1974              5576.514583

In [2]:
X = df[['year']]
y = df['per capita income (US$)']

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)
print("First 5 rows of X:\n", X.head())
print("First 5 rows of y:\n", y.head())

Shape of X: (47, 1)
Shape of y: (47,)
First 5 rows of X:
    year
0  1970
1  1971
2  1972
3  1973
4  1974
First 5 rows of y:
 0    3399.299037
1    3768.297935
2    4251.175484
3    4804.463248
4    5576.514583
Name: per capita income (US$), dtype: float64

In [3]:
from sklearn.linear_model import LinearRegression

# Create a Linear Regression model object
reg = LinearRegression()

# Train the model using the training sets X and y
reg.fit(X, y)

# Print the coefficient and intercept
print("Coefficient:", reg.coef_[0])
print("Intercept:", reg.intercept_)

Coefficient: 828.4650752227104
Intercept: -1632210.7578554575

In [4]:
year_2020 = [[2020]]
predicted_income_2020 = reg.predict(year_2020)
print(f"Predicted per capita income for 2020: {predicted_income_2020[0]:,.2f} US$")

Predicted per capita income for 2020: 41,288.69 US$

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [5]:
import pandas as pd
year_2020_df = pd.DataFrame({'year': [2020]})
predicted_income_2020 = reg.predict(year_2020_df)
print(f"Predicted per capita income for 2020: {predicted_income_2020[0]:,.2f} US$")

Predicted per capita income for 2020: 41,288.69 US$

In [7]:
import pandas as pd
import numpy as np

# Load the dataset into a pandas DataFrame
df = pd.read_csv('/content/canada_per_capita_income.csv')

# Extract 'year' and convert to NumPy array
years_np = df['year'].values

# Extract 'per capita income (US$)' and convert to NumPy array
income_np = df['per capita income (US$)'].values

# Print the first 5 elements of both arrays
print("First 5 years (NumPy array):", years_np[:5])
print("First 5 per capita incomes (NumPy array):", income_np[:5])

First 5 years (NumPy array): [1970 1971 1972 1973 1974]
First 5 per capita incomes (NumPy array): [3399.299037 3768.297935 4251.175484 4804.463248 5576.514583]

In [8]:
X_with_bias = np.c_[np.ones(years_np.shape[0]), years_np]

print("Shape of X with bias:", X_with_bias.shape)
print("First 5 rows of X with bias:\n", X_with_bias[:5])

Shape of X with bias: (47, 2)
First 5 rows of X with bias:
 [[1.000e+00 1.970e+03]
 [1.000e+00 1.971e+03]
 [1.000e+00 1.972e+03]
 [1.000e+00 1.973e+03]
 [1.000e+00 1.974e+03]]

In [9]:
X_T = X_with_bias.T
X_T_X = X_T.dot(X_with_bias)
X_T_X_inv = np.linalg.inv(X_T_X)
X_T_y = X_T.dot(income_np)
theta = X_T_X_inv.dot(X_T_y)

intercept = theta[0]
slope = theta[1]

print(f"Calculated Intercept: {intercept}")
print(f"Calculated Slope: {slope}")

Calculated Intercept: -1632210.7578560957
Calculated Slope: 828.4650752230197

In [10]:
year_2020_np = np.array([2020])

# Add a bias term to the year_2020_np to match the format of X_with_bias
year_2020_with_bias = np.c_[np.ones(year_2020_np.shape[0]), year_2020_np]

# Calculate the predicted per capita income for 2020 using the calculated intercept and slope
predicted_income_2020_np = intercept + slope * year_2020_np[0]

print(f"Predicted per capita income for 2020 (NumPy): {predicted_income_2020_np:,.2f} US$")

Predicted per capita income for 2020 (NumPy): 41,288.69 US$

In [12]:
import pandas as pd
df = pd.read_csv('/content/salary.csv')
df.head()

   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [13]:
print("DataFrame Info:")
df.info()

print("\nDescriptive Statistics:")
df.describe()

print("\nMissing Values:")
df.isnull().sum()

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  28 non-null     float64
 1   Salary           30 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes

Descriptive Statistics:

Missing Values:

YearsExperience    2
Salary             0
dtype: int64

In [14]:
print("Descriptive Statistics:")
df.describe()

Descriptive Statistics:

       YearsExperience         Salary
count        28.000000      30.000000
mean          5.192857   76003.000000
std           2.821600   27414.429785
min           1.100000   37731.000000
25%           3.150000   56720.750000
50%           4.500000   65237.000000
75%           7.300000  100544.750000
max          10.500000  122391.000000

In [15]:
df.dropna(subset=['YearsExperience'], inplace=True)
print("DataFrame Info after dropping NaNs:")
df.info()

print("\nMissing Values after dropping NaNs:")
df.isnull().sum()

DataFrame Info after dropping NaNs:
<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  28 non-null     float64
 1   Salary           28 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 672.0 bytes

Missing Values after dropping NaNs:

YearsExperience    0
Salary             0
dtype: int64

In [16]:
X = df[['YearsExperience']]
y = df['Salary']

# Reshape X if necessary (though already a DataFrame with one column, .values.reshape(-1,1) is a common explicit step)
X = X.values.reshape(-1, 1)

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)
print("First 5 rows of X:\n", X[:5])
print("First 5 rows of y:\n", y.head())

Shape of X: (28, 1)
Shape of y: (28,)
First 5 rows of X:
 [[1.1]
 [1.3]
 [1.5]
 [2. ]
 [2.2]]
First 5 rows of y:
 0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [17]:
from sklearn.linear_model import LinearRegression

# Instantiate a Linear Regression model object
regressor = LinearRegression()

# Train the model using the prepared X and y data
regressor.fit(X, y)

# Print the learned coefficient (slope) and intercept
print(f"Coefficient (slope): {regressor.coef_[0]:.2f}")
print(f"Intercept: {regressor.intercept_:.2f}")

Coefficient (slope): 9398.64
Intercept: 26265.99

In [18]:
import numpy as np

# Create a NumPy array for 12 years of experience and reshape it
years_of_experience = np.array([[12]])

# Predict the salary using the trained regressor model
predicted_salary = regressor.predict(years_of_experience)

# Print the predicted salary, formatted to two decimal places
print(f"Predicted Salary for 12 Years Experience: ${predicted_salary[0]:,.2f}")

Predicted Salary for 12 Years Experience: $139,049.67

In [20]:
import pandas as pd
import numpy as np

# Load the dataset into a pandas DataFrame
df_salary = pd.read_csv('/content/salary.csv')

# Handle missing values in 'YearsExperience'
df_salary.dropna(subset=['YearsExperience'], inplace=True)

# Extract 'YearsExperience' and convert to NumPy array
years_exp_np = df_salary['YearsExperience'].values

# Extract 'Salary' and convert to NumPy array
salary_np = df_salary['Salary'].values

# Add a bias term to the years_exp_np array
X_salary_with_bias = np.c_[np.ones(years_exp_np.shape[0]), years_exp_np]

print("Shape of X_salary_with_bias:", X_salary_with_bias.shape)
print("First 5 rows of X_salary_with_bias:\n", X_salary_with_bias[:5])
print("Shape of salary_np:", salary_np.shape)
print("First 5 elements of salary_np:", salary_np[:5])

Shape of X_salary_with_bias: (28, 2)
First 5 rows of X_salary_with_bias:
 [[1.  1.1]
 [1.  1.3]
 [1.  1.5]
 [1.  2. ]
 [1.  2.2]]
Shape of salary_np: (28,)
First 5 elements of salary_np: [39343 46205 37731 43525 39891]

In [21]:
# Calculate coefficients using the normal equation
X_T_salary = X_salary_with_bias.T
X_T_X_salary = X_T_salary.dot(X_salary_with_bias)
X_T_X_inv_salary = np.linalg.inv(X_T_X_salary)
X_T_y_salary = X_T_salary.dot(salary_np)
theta_salary = X_T_X_inv_salary.dot(X_T_y_salary)

intercept_salary = theta_salary[0]
slope_salary = theta_salary[1]

print(f"Calculated Intercept (NumPy): {intercept_salary:.2f}")
print(f"Calculated Slope (NumPy): {slope_salary:.2f}")

Calculated Intercept (NumPy): 26265.99
Calculated Slope (NumPy): 9398.64

In [22]:
# Predict salary for 12 years of experience
years_to_predict = np.array([12])
predicted_salary_np_only = intercept_salary + slope_salary * years_to_predict[0]

print(f"Predicted Salary for {years_to_predict[0]} Years Experience (NumPy): ${predicted_salary_np_only:,.2f}")

Predicted Salary for 12 Years Experience (NumPy): $139,049.67

In [23]:
import pandas as pd
df_hiring = pd.read_csv('/content/hiring.csv')
df_hiring.head()

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [27]:
df_hiring['experience'] = df_hiring['experience'].astype(float)
median_experience = df_hiring['experience'].median()
df_hiring['experience'] = df_hiring['experience'].fillna(median_experience)

# Select feature columns and target column, explicitly creating a copy to avoid SettingWithCopyWarning
X_hiring = df_hiring[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']].copy()
y_hiring = df_hiring['salary($)'].copy()

# Convert test_score and interview_score to numeric, handle NaNs
X_hiring['test_score(out of 10)'] = pd.to_numeric(X_hiring['test_score(out of 10)'], errors='coerce')
median_test_score = X_hiring['test_score(out of 10)'].median()
X_hiring['test_score(out of 10)'] = X_hiring['test_score(out of 10)'].fillna(median_test_score)

X_hiring['interview_score(out of 10)'] = pd.to_numeric(X_hiring['interview_score(out of 10)'], errors='coerce')
median_interview_score = X_hiring['interview_score(out of 10)'].median()
X_hiring['interview_score(out of 10)'] = X_hiring['interview_score(out of 10)'].fillna(median_interview_score)

# Convert to NumPy arrays
X_hiring_np = X_hiring.values
y_hiring_np = y_hiring.values

# Add a bias term (column of ones) to X_hiring_np
X_hiring_biased = np.c_[np.ones(X_hiring_np.shape[0]), X_hiring_np]

# Calculate coefficients using the normal equation
X_T_X = X_hiring_biased.T @ X_hiring_biased
X_T_X_inv = np.linalg.inv(X_T_X)
X_T_y = X_hiring_biased.T @ y_hiring_np
theta_hiring = X_T_X_inv @ X_T_y

print("Shape of X_hiring_biased:", X_hiring_biased.shape)
print("First 5 rows of X_hiring_biased:\n", X_hiring_biased[:5])
print("Calculated Coefficients (theta_hiring):", theta_hiring)

Shape of X_hiring_biased: (8, 4)
First 5 rows of X_hiring_biased:
 [[ 1.  6.  8.  9.]
 [ 1.  6.  8.  6.]
 [ 1.  5.  6.  7.]
 [ 1.  2. 10. 10.]
 [ 1.  7.  9.  6.]]
Calculated Coefficients (theta_hiring): [11869.91869919  2813.00813008  1333.33333333  2926.82926829]

In [28]:
import numpy as np

# Features for the first candidate: 2 years experience, 9 test score, 6 interview score
candidate1_features = np.array([2, 9, 6])

# Add a bias term to the candidate's features
candidate1_biased = np.insert(candidate1_features, 0, 1)

# Predict the salary for the first candidate
predicted_salary_candidate1 = candidate1_biased @ theta_hiring

print(f"Predicted Salary for Candidate 1 (2 yrs exp, 9 test, 6 interview): ${predicted_salary_candidate1:,.2f}")

Predicted Salary for Candidate 1 (2 yrs exp, 9 test, 6 interview): $47,056.91

In [29]:
import numpy as np

# Features for the second candidate: 12 years experience, 10 test score, 10 interview score
candidate2_features = np.array([12, 10, 10])

# Add a bias term to the candidate's features
candidate2_biased = np.insert(candidate2_features, 0, 1)

# Predict the salary for the second candidate
predicted_salary_candidate2 = candidate2_biased @ theta_hiring

print(f"Predicted Salary for Candidate 2 (12 yrs exp, 10 test, 10 interview): ${predicted_salary_candidate2:,.2f}")

Predicted Salary for Candidate 2 (12 yrs exp, 10 test, 10 interview): $88,227.64

In [31]:
import pandas as pd
df_companies = pd.read_csv('/content/1000_Companies.csv')
df_companies.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [32]:
X_companies = df_companies[['R&D Spend', 'Administration', 'Marketing Spend', 'State']]
y_companies = df_companies['Profit']

print("Features (X_companies) head:\n", X_companies.head())
print("\nTarget (y_companies) head:\n", y_companies.head())

Features (X_companies) head:
    R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

Target (y_companies) head:
 0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [33]:
X_companies_encoded = pd.get_dummies(X_companies, columns=['State'], drop_first=True)

print("Features (X_companies_encoded) head after one-hot encoding:\n", X_companies_encoded.head())
print("Shape of X_companies_encoded:", X_companies_encoded.shape)

Features (X_companies_encoded) head after one-hot encoding:
    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10          False            True
1  162597.70       151377.59        443898.53          False           False
2  153441.51       101145.55        407934.54           True           False
3  144372.41       118671.85        383199.62          False            True
4  142107.34        91391.77        366168.42           True           False
Shape of X_companies_encoded: (1000, 5)

In [34]:
from sklearn.linear_model import LinearRegression

# Instantiate a Linear Regression model
model_companies = LinearRegression()

print("LinearRegression model instantiated successfully.")

LinearRegression model instantiated successfully.

In [35]:
model_companies.fit(X_companies_encoded, y_companies)

print("Linear Regression model for companies trained successfully.")

Linear Regression model for companies trained successfully.

In [36]:
new_company_data = pd.DataFrame({
    'R&D Spend': [160000],
    'Administration': [130000],
    'Marketing Spend': [300000],
    'State': ['California']
})

print("New company data DataFrame:")
print(new_company_data)

New company data DataFrame:
   R&D Spend  Administration  Marketing Spend       State
0     160000          130000           300000  California

In [37]:
new_company_data_encoded = pd.get_dummies(new_company_data, columns=['State'], drop_first=True)

# Align columns of new data with the training data's encoded columns
# This ensures that if a state is missing in the new data but present in training, or vice versa,
# the column structure remains consistent.
missing_cols = set(X_companies_encoded.columns) - set(new_company_data_encoded.columns)
for c in missing_cols:
    new_company_data_encoded[c] = 0
new_company_data_encoded = new_company_data_encoded[X_companies_encoded.columns]

print("New company data after one-hot encoding and alignment:")
print(new_company_data_encoded)

New company data after one-hot encoding and alignment:
   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0     160000          130000           300000              0               0

In [38]:
predicted_profit = model_companies.predict(new_company_data_encoded)

print(f"Predicted Profit for the new company: ${predicted_profit[0]:,.2f}")

Predicted Profit for the new company: $176,190.56